// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: mediaplayer.proto

package mediaplayer

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SetVolumeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Volume float32 `protobuf:"fixed32,1,opt,name=volume,proto3" json:"volume,omitempty"`
}

func (x *SetVolumeReq) Reset() {
	*x = SetVolumeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mediaplayer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetVolumeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVolumeReq) ProtoMessage() {}

func (x *SetVolumeReq) ProtoReflect() protoreflect.Message {
	mi := &file_mediaplayer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVolumeReq.ProtoReflect.Descriptor instead.
func (*SetVolumeReq) Descriptor() ([]byte, []int) {
	return file_mediaplayer_proto_rawDescGZIP(), []int{0}
}

func (x *SetVolumeReq) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type SetVolumeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetVolumeRes) Reset() {
	*x = SetVolumeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mediaplayer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetVolumeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetVolumeRes) ProtoMessage() {}

func (x *SetVolumeRes) ProtoReflect() protoreflect.Message {
	mi := &file_mediaplayer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetVolumeRes.ProtoReflect.Descriptor instead.
func (*SetVolumeRes) Descriptor() ([]byte, []int) {
	return file_mediaplayer_proto_rawDescGZIP(), []int{1}
}

type StreamUpdatesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StreamUpdatesReq) Reset() {
	*x = StreamUpdatesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mediaplayer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamUpdatesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamUpdatesReq) ProtoMessage() {}

func (x *StreamUpdatesReq) ProtoReflect() protoreflect.Message {
	mi := &file_mediaplayer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamUpdatesReq.ProtoReflect.Descriptor instead.
func (*StreamUpdatesReq) Descriptor() ([]byte, []int) {
	return file_mediaplayer_proto_rawDescGZIP(), []int{2}
}

type Update struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Volume float32 `protobuf:"fixed32,1,opt,name=volume,proto3" json:"volume,omitempty"`
	Muted  bool    `protobuf:"varint,2,opt,name=muted,proto3" json:"muted,omitempty"`
}

func (x *Update) Reset() {
	*x = Update{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mediaplayer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_mediaplayer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_mediaplayer_proto_rawDescGZIP(), []int{3}
}

func (x *Update) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *Update) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

var File_mediaplayer_proto protoreflect.FileDescriptor

var file_mediaplayer_proto_rawDesc = []byte{
	0x0a, 0x11, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x22, 0x26, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x22, 0x0e, 0x0a, 0x0c, 0x53, 0x65, 0x74, 0x56,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x22, 0x36, 0x0a, 0x06,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6d,
	0x75, 0x74, 0x65, 0x64, 0x32, 0x9b, 0x01, 0x0a, 0x0b, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x12, 0x43, 0x0a, 0x09, 0x53, 0x65, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x12, 0x19, 0x2e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e,
	0x53, 0x65, 0x74, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x19, 0x2e, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x56, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x0d, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x50, 0x0a, 0x1b, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c,
	0x64, 0x42, 0x0f, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x57, 0x6f, 0x72, 0x6c, 0x64, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6d, 0x64, 0x75, 0x62, 0x62, 0x38, 0x36, 0x2f, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mediaplayer_proto_rawDescOnce sync.Once
	file_mediaplayer_proto_rawDescData = file_mediaplayer_proto_rawDesc
)

func file_mediaplayer_proto_rawDescGZIP() []byte {
	file_mediaplayer_proto_rawDescOnce.Do(func() {
		file_mediaplayer_proto_rawDescData = protoimpl.X.CompressGZIP(file_mediaplayer_proto_rawDescData)
	})
	return file_mediaplayer_proto_rawDescData
}

var file_mediaplayer_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mediaplayer_proto_goTypes = []interface{}{
	(*SetVolumeReq)(nil),     // 0: mediaplayer.SetVolumeReq
	(*SetVolumeRes)(nil),     // 1: mediaplayer.SetVolumeRes
	(*StreamUpdatesReq)(nil), // 2: mediaplayer.StreamUpdatesReq
	(*Update)(nil),           // 3: mediaplayer.Update
}
var file_mediaplayer_proto_depIdxs = []int32{
	0, // 0: mediaplayer.MediaPlayer.SetVolume:input_type -> mediaplayer.SetVolumeReq
	2, // 1: mediaplayer.MediaPlayer.StreamUpdates:input_type -> mediaplayer.StreamUpdatesReq
	1, // 2: mediaplayer.MediaPlayer.SetVolume:output_type -> mediaplayer.SetVolumeRes
	3, // 3: mediaplayer.MediaPlayer.StreamUpdates:output_type -> mediaplayer.Update
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mediaplayer_proto_init() }
func file_mediaplayer_proto_init() {
	if File_mediaplayer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mediaplayer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetVolumeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mediaplayer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetVolumeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mediaplayer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamUpdatesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mediaplayer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Update); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mediaplayer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mediaplayer_proto_goTypes,
		DependencyIndexes: file_mediaplayer_proto_depIdxs,
		MessageInfos:      file_mediaplayer_proto_msgTypes,
	}.Build()
	File_mediaplayer_proto = out.File
	file_mediaplayer_proto_rawDesc = nil
	file_mediaplayer_proto_goTypes = nil
	file_mediaplayer_proto_depIdxs = nil
}
