# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mediaplayer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mediaplayer.proto',
  package='mediaplayer',
  syntax='proto3',
  serialized_options=b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001Z\036github.com/mdubb86/mediaplayer',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11mediaplayer.proto\x12\x0bmediaplayer\"\x18\n\x06SetReq\x12\x0e\n\x06volume\x18\x01 \x01(\x02\"\x18\n\x06Update\x12\x0e\n\x06volume\x18\x01 \x01(\x02\x32L\n\x0bMediaPlayer\x12=\n\x0b\x43ommunicate\x12\x13.mediaplayer.SetReq\x1a\x13.mediaplayer.Update\"\x00(\x01\x30\x01\x42P\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01Z\x1egithub.com/mdubb86/mediaplayerb\x06proto3'
)




_SETREQ = _descriptor.Descriptor(
  name='SetReq',
  full_name='mediaplayer.SetReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume', full_name='mediaplayer.SetReq.volume', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=58,
)


_UPDATE = _descriptor.Descriptor(
  name='Update',
  full_name='mediaplayer.Update',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='volume', full_name='mediaplayer.Update.volume', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=84,
)

DESCRIPTOR.message_types_by_name['SetReq'] = _SETREQ
DESCRIPTOR.message_types_by_name['Update'] = _UPDATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetReq = _reflection.GeneratedProtocolMessageType('SetReq', (_message.Message,), {
  'DESCRIPTOR' : _SETREQ,
  '__module__' : 'mediaplayer_pb2'
  # @@protoc_insertion_point(class_scope:mediaplayer.SetReq)
  })
_sym_db.RegisterMessage(SetReq)

Update = _reflection.GeneratedProtocolMessageType('Update', (_message.Message,), {
  'DESCRIPTOR' : _UPDATE,
  '__module__' : 'mediaplayer_pb2'
  # @@protoc_insertion_point(class_scope:mediaplayer.Update)
  })
_sym_db.RegisterMessage(Update)


DESCRIPTOR._options = None

_MEDIAPLAYER = _descriptor.ServiceDescriptor(
  name='MediaPlayer',
  full_name='mediaplayer.MediaPlayer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=86,
  serialized_end=162,
  methods=[
  _descriptor.MethodDescriptor(
    name='Communicate',
    full_name='mediaplayer.MediaPlayer.Communicate',
    index=0,
    containing_service=None,
    input_type=_SETREQ,
    output_type=_UPDATE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEDIAPLAYER)

DESCRIPTOR.services_by_name['MediaPlayer'] = _MEDIAPLAYER

# @@protoc_insertion_point(module_scope)
